version: 2
jobs:
  macosx:
    docker:
      - image: nimlang/nim:latest
    working_directory: /usr/src/vendor
    steps:
      - checkout
      - run:
          name: provision
          command: |
            apt install -y make;
            make provision os=macosx
      - run:
          name: semver
          command: |
            cd ..
            git clone https://github.com/shishidosoichiro/semver.nim.git
            cd semver.nim
            nimble install -y
            cd ../vendor
      - run:
          name: nimble
          command: nimble install -y
      - run:
          name: build
          command: |
            export PATH="$PATH:/usr/src/vendor/osxcross/target/bin";
            make macosx
      - store_artifacts:
          path: /usr/src/vendor/dist/vendor-0.3.2-macosx-amd64.tar.gz
  linux:
    docker:
      - image: nimlang/nim:latest
    working_directory: /usr/src/vendor
    steps:
      - checkout
      - run:
          name: provision
          command: |
            apt install -y make;
            make provision os=linux
      - run:
          name: semver
          command: |
            cd ..
            git clone https://github.com/shishidosoichiro/semver.nim.git
            cd semver.nim
            nimble install -y
            cd ../vendor
      - run:
          name: nimble
          command: nimble install -y
      - run:
          name: build
          command: make linux
      - store_artifacts:
          path: /usr/src/vendor/dist/vendor-0.3.2-linux-amd64.tar.gz
  windows:
    docker:
      - image: nimlang/nim:latest
    working_directory: /usr/src/vendor
    steps:
      - checkout
      - run:
          name: provision
          command: |
            apt install -y make;
            make provision os=windows
      - run:
          name: semver
          command: |
            cd ..
            git clone https://github.com/shishidosoichiro/semver.nim.git
            cd semver.nim
            nimble install -y
            cd ../vendor
      - run:
          name: nimble
          command: nimble install -y
      - run:
          name: build
          command: make windows
      - store_artifacts:
          path: /usr/src/vendor/dist/vendor-0.3.2-windows-amd64.zip
workflows:
  version: 2
  build:
    jobs:
      - macosx
      - linux
      - windows
